### ISSUE TITLE
Duda con la imagen para la creación del cmatrix

### ISSUE THREAD

**Issue by DaviidFdez** [DaviidFdez/Tarea-Evaluable-Docker#2]

**Comment by diegodir92** [comment]
Problemas con el docker-compose de cmatrix: el contenedor se ejecuta pero no se consigue mostrar el efecto _Greenrain_.

**Comment by diegodir92** [comment]
Tras la busqueda de información y a nuestro compañero Sergio le funciono el docker-compose de la imagen _cmatrix_, por lo que utilizando su imagen subida a dockerhub conseguimos realizar la parte que faltaba.
