### ISSUE TITLE
Problemas con la versión del docker portainer

### ISSUE THREAD

**Issue by diegodir92** [DaviidFdez/Tarea-Evaluable-Docker#3]
Para realizar el segundo ejercicio a sido necesario acceder al docker portainer mediante docker-compose, debido a que al no acceder por este, se requiere  una licencia para usarlo.

**Comment by DaviidFdez** [comment]
Mi grupo y yo hemos investigado que habia una serie de versiones de la imagen portainer en la cual no servian para el docker-compose. Al escribir esta linea de comando ya se ejecutaba la imagen perfectamente => image: portainer/portainer-ce:latest
